In [1]:
#Python as Calculator:

#Multiplication
print(3 * 5)

#Division
print(10 / 2)

#Reminder
print(18 % 7)

#Exponential

print(4 ** 2)


15
5.0
4
16


In [27]:
#Variable storage:

k = 3
m = 5

print(k*m)

15


int

In [32]:
#Variable Types:

a = 2
print(type(a))

b = 3.0
print(type(b))

c = 'saurabh'
print(type(c))

d = True
print(type(d))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [35]:
#Variable addition:

print(2+4)
print('ab' + 'cd')
print('2'+'4')

6
abcd
24


In [41]:
# Importance of conversion (following code throws error):
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + savings + " and now have $" + result + ". Awesome!")


TypeError: can only concatenate str (not "int") to str

In [43]:
# Importance of conversion (following code doesnt throw error):
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

I started with $100 and now have $194.87171000000012. Awesome!


In [9]:
# Lists :
# Instead of creating different variable for each number, its better to create  list:

#Consider following example of heights in family:

fam = [1.73, 1.68, 1.71, 1.89]

print(fam)

#Lists can also hold different variable types:

fam2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89] 
print(fam2)

#Lists can also contain lists:

fam3 = [["liz", 1.73],                  ["emma", 1.68],                  ["mom", 1.71],                  ["dad", 1.89]] 
print(fam3)



[1.73, 1.68, 1.71, 1.89]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
[['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]


In [16]:
#Subsetting the lists:

#Indexing: 

#In python indexing starts from 0 from front and from -1 from end:

fam2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89] 
print(fam2)

print (fam2[0])
print (fam2[-1])


['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
liz
1.89


In [28]:
# Slicing the list:

fam2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89] 
print(fam2)
# [ start : end ] = inclusive exclusive

print (fam2[3:5])
print (fam2[1:4])
print(fam2[:3])
print(fam2[5:])

#To print the first four elements:

print(fam2[:4])

#To print last four elements of list:

print(fam2[-4:])


['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
[1.68, 'mom']
[1.73, 'emma', 1.68]
['liz', 1.73, 'emma']
[1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68]
['mom', 1.71, 'dad', 1.89]


In [7]:
#List Manipulation:

fam2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam2)

#If we want to change 1.89 to 1.86:

fam2[-1] = 1.86
print(fam2)


['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]


In [12]:
#If we want to change 1st two elements in the list:

fam2[:2] = ['lisa', 1.74]
print(fam2)

#If we want add new elements to the list:

fam2_ext = fam2 + ['me', 1.79]
print(fam2_ext)

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]
['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]


In [18]:
fam2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

#If we want to delete 3rd element in the list:

del(fam2[2])
print(fam2)

#If we again delete the 3rd element, result will e as follows:
del(fam2[2])
print(fam2)

['liz', 1.73, 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'mom', 1.71, 'dad', 1.89]


In [21]:
# Behind the scenes:

x = ['a', 'b', 'c']
print(x)

#Let's try to copy the list from one list to other:
y = x

#Lets change the element and check both the lists:
y[1] = 'z'
print(y)
print(x)

['a', 'b', 'c']
['a', 'z', 'c']
['a', 'z', 'c']


In [31]:
#So from the above results, we can see that along with the contets in y, contents in x are also changed,
#This is coz, when we tried to copy x to y with the equal sign, we copied the reference to the list, not actual value themselves.
#So both the lists point to the same address so the same values

#So for copying the list, we need to use following syntax:

x = ['a', 'b', 'c']

y = x[:]

print('y:',y)

#Lets change the element and check both the lists:
y[1] = 'z'

print('y (after changing the element):',y)
print('x:',x)


y: ['a', 'b', 'c']
y (after changing the element): ['a', 'z', 'c']
x: ['a', 'b', 'c']


In [38]:
# Functions:

fam = [1.73, 1.68, 1.71, 1.89]
print(fam)

#Max, min function:

print(max(fam))
print(min(fam))

[1.73, 1.68, 1.71, 1.89]
1.89
1.68


In [40]:
#Round Function:

round(2.7632, 2)

2.76

In [42]:
round(2.972)

3

In [44]:
round(2.09283, 3)

2.093

In [48]:
#Ascending, Descending order of the list:

# Sort function:

#Ascending:
print(sorted(fam))

#Descending:
print(sorted(fam, reverse = True))


[1.68, 1.71, 1.73, 1.89]
[1.89, 1.73, 1.71, 1.68]


In [52]:
#Methods:

fam2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

#Checking index of particular element in the list:

fam2.index('mom')

#'index' method is available both for index and lists

4

In [54]:
#Count a particular number of element in a list:
fam2.count(1.73)

1

In [75]:
#String manipulation:

name = 'liz'

#Capitalize first letter:
print(name.capitalize())
      
#Capitalize all letters in name:
print(name.upper())      # Similarly name.lower() will decapitize the name

#Replace letter in name:

print(name.replace('z', 'sa'))

#Note: 'replace' doesnt work for lists

Liz
LIZ
lisa


In [71]:
#append:

#append is used to add the element in the list:

fam2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print('Old:',fam2)

fam2.append('me')
print('New1:',fam2)

fam2.append(1.79)
print('New2:',fam2)

Old: ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
New1: ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me']
New2: ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.79]


In [7]:
#remove():

fam2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam2)

fam2.remove(1.89)
print(fam2)

fam2.remove(fam2[1])
print(fam2)


['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad']
['liz', 'emma', 1.68, 'mom', 1.71, 'dad']


In [14]:
#Reverse():

fam2 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
fam3 = fam2.reverse()
print(fam2)
print(fam3)

[1.89, 'dad', 1.71, 'mom', 1.68, 'emma', 1.73, 'liz']
None


In [ ]:
•	 #Difference between Lists and array?
#Lists can contain elements with different data type. Array can contain only numerical elements
•	 #Why do we need numpy array if we have lists?
#Lists cannot perform mathematical operations. Lists give error if we try to perform mathematical operations with 2 or more lists.
#But array can perform mathematical operations and that’s why we need arrays.


In [17]:
import numpy
array([1,2,3])

NameError: name 'array' is not defined

In [18]:
#Above code is throwing error.
#So we always needs to write the np (after importing numpy as np).

numpy.array([1,2,3])

array([1, 2, 3])

In [20]:
#For short cut we can use np instead of numpy:

import numpy as np

np.array([1,2,3])

array([1, 2, 3])

In [26]:
#Or we can also directly import array from numpy (which is not recommended coz in long code, 
#we dont understand in which package it fits):

from numpy import array
array([1,2,3])

array([1, 2, 3])

In [28]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight / height ** 2


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [29]:
#Above code is throwing error as we are expecting that lists should perform mathematical opearations:

#Mathematical operations can be performed as follows then:

np_height = np.array(height)
np_weight = np.array(weight)
np_weight / np_height ** 2
array([ 21.852, 20.975, 21.75 , 24.747, 21.441])

#In above operation, we are converting lists into array and then performing maths operations


array([21.852, 20.975, 21.75 , 24.747, 21.441])

In [25]:
#•	Different Data type have different behavior:

print(np.array([1,2,3]) + np.array([1,2,3]))

print([1,2,3] + [1,2,3])

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [32]:
# Numpy subsetting:

bmi = np.array([ 21.852, 20.975, 21.75 , 24.747, 21.441])

#To select particular element in the array
print(bmi[1])

#To check whether which elements are greater or smaller than a particular element
print(bmi > 23)

#To print numbers greater or smaller than a particular number
print(bmi[bmi > 23])


20.975
[False False False  True False]
[24.747]


In [40]:
# 2D Numpy arrays:

np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
 [65.4, 59.2, 63.6, 88.4, 68.7]]) 

print(np_2d)


[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


In [45]:
# To check the dimension of te array:

np_2d.shape

(2, 5)

In [47]:
#Lets try to add an alphabetical character in the array:

np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
 [65.4, 59.2, 63.6, 88.4, "68.7"]]) 

#So from the output we can see that numbers are converted into characters. So only single data type is allowed in the array

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [53]:
#2d array subsetting:

print(np_2d[0])

print(np_2d[0][2])
print(np_2d[0,2])

#So both the above 2 lines give same 

print (np_2d[:,1:3])   # This line indicates all rows and 2nd,3rd column

print(np_2d[1, :])   # This line indicates first row and columns

[1.73 1.68 1.71 1.89 1.79]
1.71
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]


In [65]:
# 2d array arithmetic opearations:

array1 = np.array([[1,1,1], [0,0,0]])
print(array1)

array2 = np.array([[2,2,2], [-1,-1,-1]])
print(array2)

print(array1 + array2)

[[1 1 1]
 [0 0 0]]
[[ 2  2  2]
 [-1 -1 -1]]
[[ 3  3  3]
 [-1 -1 -1]]


In [77]:
# Basic Statistics with Numpy:

#First create random samples and create the two datasets:

np_height = np.random.normal(1.5, 0.2, 2000)  #First number is mean, second is standard dev and third is number of samples
#print(np_height)
np_weight = np.random.normal(60, 20, 2000)
#print(np_weight)

np_city = np.column_stack((np_height, np_weight))  # Note this double bracket, single bracket will throw error
print(np_city)

[[ 2.05417769 20.07744339]
 [ 1.47439889 27.96800891]
 [ 2.01201112 67.36533938]
 ...
 [ 1.39027168 58.69489768]
 [ 1.59640093 72.27446477]
 [ 1.44566393 60.1730549 ]]


In [81]:
#To find mean of the height:

print(np.mean(np_city[:,0]))

#To find median of the height:
print(np.median(np_city[0,:]))

#Same we can do for weight

1.500103802202642
11.065810540647565


In [85]:
#To find correlation between height and weight:

np.corrcoef(np_city[:,0], np_city[:,1])


array([[ 1.        , -0.03387967],
       [-0.03387967,  1.        ]])

In [87]:
# To find the standard deviation:

np.std(np_city[:,0])


0.19686534055775157